### ISSUE TITLE
Add new icons

### ISSUE THREAD

**Issue by copsho** [wiliamvj/Portfolio-in-Construction#1]
Hello,

Add new social media icons?

**Comment by wiliamvj** [comment]
Hi, Yes! 

Just access this site [here](https://react-icons.netlify.app/#/icons/fi).

Search for the desired icon, copy your `FiHome` code for example.

Then import it into the `App.js` file.

`import {FiGithub, FiLinkedin} from 'react-icons / fi';`

Then just create the tag with the link code for example `<FiHome />`

Within this tag you can still pass some attributes, such as color and size for example.

`<FiHome className="icon" size={56} color="rgb(98, 114, 164)" />`
